server {
    listen 80;
    server_name hz.jc-times.com;

    location / {
        proxy_pass http://host.docker.internal:3000; # 代理到宿主机的 3000 端口
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}